In [1]:
db=[1, "vimal" , "ok"]

In [2]:
db

[1, 'vimal', 'ok']

In [3]:
db.append(1111)

In [4]:
db

[1, 'vimal', 'ok', 1111]

In [5]:
db=[[1,"vimal",1111,"ok"] , [2,"jack",2222,"good"] , [3,"jane",3333,"vgood"] , [4,"eric",4444,"ok"]]

In [6]:
db[2][2]

3333

In [7]:
db[1:3]

[[2, 'jack', 2222, 'good'], [3, 'jane', 3333, 'vgood']]

In [8]:
import numpy

In [9]:
a=numpy.array(db)

In [10]:
a

array([['1', 'vimal', '1111', 'ok'],
       ['2', 'jack', '2222', 'good'],
       ['3', 'jane', '3333', 'vgood'],
       ['4', 'eric', '4444', 'ok']], dtype='<U11')

In [11]:
type(a)

numpy.ndarray

In [12]:
a[1:3,1:3]

array([['jack', '2222'],
       ['jane', '3333']], dtype='<U11')

In [13]:
a.shape

(4, 4)

In [14]:
a1=numpy.array([1,2,3,4,5,6,7,8])

In [15]:
a1.shape

(8,)

In [16]:
a1.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
a1.reshape(1,8)

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [18]:
a1.reshape(8,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [19]:
a1.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [20]:
a1.reshape(-1,1).shape

(8, 1)